[package]

name = "portaudio_sys"
version = "0.1.1"
authors = ["Mathijs van de Nes <git@mathijs.vd-nes.nl>"]
links = "portaudio"

[lib]
name = "portaudio_sys"
path = "lib.rs"

[build-dependencies]
pkg-config = "^0.3.3"

[dependencies]
libc = "0.2"
